---
title: "Leafs"
author: "Kaisa Roggeveen, Scott Graham"
date: "March 22nd 2018"
header-includes:
  - \newcommand{\Prob}{\operatorname{P}}
  - \newcommand{\E}{\operatorname{E}}
  - \newcommand{\Var}{\operatorname{Var}}
  - \newcommand{\Cov}{\operatorname{Cov}}
  - \newcommand{\se}{\operatorname{se}}
  - \newcommand{\re}{\operatorname{re}}
  - \newcommand{\ybar}{{\overline{Y}}}
  - \newcommand{\phat}{{\hat{p}}}
  - \newcommand{\that}{{\hat{T}}}
  - \newcommand{\med}{{\tilde{Y}}}
  - \newcommand{\logit}{{\operatorname{Logit}}}
output: 
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(pander, warn.conflicts = FALSE, quietly = TRUE)
library(knitr, warn.conflicts = FALSE, quietly = TRUE)
library(MASS, warn.conflicts = FALSE, quietly = TRUE)
library(tidyverse, warn.conflicts = FALSE, quietly = TRUE)
library(magrittr, warn.conflicts = FALSE, quietly = TRUE)
library(ggfortify, warn.conflicts = FALSE, quietly = TRUE)

theme_minimal2 <- theme_minimal() %>%  theme_set()
theme_minimal2 <-
  theme_update(
    panel.border = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
    ,strip.background = element_rect(
      linetype = "solid"
      ,colour = "grey92"
      ,fill = NA
    )
  )

# Functions ----------
geom_cor <- function(data, ...){
  data %>%
    filter_all(any_vars(!is.na(.))) %>% 
    cor(...) %>% 
    as.data.frame() %>%  
    rownames_to_column() %>% 
    as.tibble() %>% 
    gather(
      key = Column
      ,value = Correlation
      ,-rowname
    ) %>% 
    rename(Row = rowname) %>% 
    ggplot(
      aes(
        x = Column
        ,y = Row
        ,fill = Correlation
      )
    ) +
    geom_raster() +
    scale_fill_distiller(
      type = "div"
      ,palette = "RdBu"
      ,limits = c(-1, 1)
    ) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1)
      ,axis.title.x = element_blank()
      ,axis.title.y = element_blank()
      ,panel.grid = element_blank()
      ,panel.background = element_blank()
    )
}

dens_gen <- function(data, leaf_type, newdata){
  data <- 
    data %>% 
    filter(Type == leaf_type)
  
  leaf_density <- kde2d(x = data$Length, y = data$Width, n = 50)#nrow(leaf_data))

  names(leaf_density) <- c(measurements, "Density")
  rownames(leaf_density$Density) <- leaf_density$Length
  colnames(leaf_density$Density) <- leaf_density$Width

  newdata <-
    newdata %>%
    bind_cols(
      newdata$Length %>%
        map_dbl(
          .f = function(x) leaf_density$Length[which(abs(leaf_density$Length - x)==min(abs(leaf_density$Length - x)))]
        ) %>%
        as_tibble() %>%
        rename(`Closest Length` = value)

      ,leaf_test$Width %>%
        map_dbl(
          function(x) leaf_density$Width[which(abs(leaf_density$Width - x)==min(abs(leaf_density$Width - x)))]
        ) %>%
        as_tibble() %>%
        rename(`Closest Width` = value)
    ) %>%
    mutate(
      `Closest Length` = round(`Closest Length`, 4)
      ,`Closest Width` = round(`Closest Width`, 4)
    )

  leaf_density_tidy <-
    leaf_density$Density %>%
    as.data.frame() %>%
    rownames_to_column() %>%
    as_tibble() %>%
    rename(Length = rowname) %>%
    gather(
      key = Width
      ,value = Density
      ,-Length
    ) %>%
    mutate_all(as.numeric) %>%
    round(4)

  leaf_density_tidy %>%
    filter(
      Length %in% newdata$`Closest Length`
      ,Width %in% newdata$`Closest Width`
    )
}

# Data Import ----------
leaf_data <- 
  "../Data/leaf_data.csv" %>% 
  read_csv() %>% 
  mutate(Type = as.factor(Type))

measurements <- c("Length", "Width")
```


# Introduction




# Data
## Measurement Process



## Data Creation
```{r Data Creation 01}
leaf_data %>% 
  select(
    Type
    ,Length
    ,Width
  ) %>% 
  kable()

leaf_data %>% 
  select(-starts_with("Number")) %>% 
  group_by(Type) %>% 
  summary() %>% 
  kable()
```



# Classification Procedure
## Training Data



## New Data



## Observation Space
```{r Obs Space 01}
leaf_data %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
      ,colour = Type
    )
  ) + 
  geom_point() +
  scale_colour_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(title = "Figure XX: Length vs Width Scatter Plot")
```

```{r Obs Space 02}
leaf_data %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
      ,colour = Type
    )
  ) + 
  geom_density_2d() +
  geom_point() +
  facet_wrap(
    ~ Type
  ) +
  scale_colour_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(
    title = "Figure XX: Length vs Width Scatter Plot"
    ,subtitle = "Overlayed with the Contour Plot"
  )

leaf_data %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
    )
  ) + 
  geom_density_2d(colour = "black") +
  geom_point(aes(colour = Type)) +
  scale_colour_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(
    title = "Figure XX: Length vs Width Scatter Plot"
    ,subtitle = "Overlayed with a Contour Plot of that Type"
    ,colour = "Type"
  )
```

```{r Obs Space 03}
leaf_data %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
      ,colour = Type
    )
  ) + 
  geom_polygon(
    data =
      leaf_data %>%
      split(.$Type) %>% 
      map(~ select(., Width, Length)) %>%
      map_df(~ chull(.)) %>% 
      gather(
        key = Type
        ,value = `Number By Type`
      ) %>% 
      mutate(Type = as.factor(Type)) %>% 
      left_join(leaf_data, by = c("Number By Type", "Type"))
    ,alpha = 0.1
  ) +
  geom_point() +
  scale_colour_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(
    title = "Figure XX: Length vs Width Scatter Plot"
    ,subtitle = "Overlayed with the Convex Hull of that Type"
  )
```

```{r Obs Space 04}
leaf_data %>% 
  select(Length, Width) %>% 
  gather(
    key = Dimension
    ,value = Measurement
  ) %>% 
  ggplot(aes(x = Measurement, y = ..density..)) +
  geom_histogram(
    alpha = 0.5
    ,binwidth = function(x) 2 * IQR(x) / (length(x)^(1/3))
  ) +
  geom_density() +
  facet_wrap(
    ~ Dimension
  ) +
  labs(title = "Figure XX: Density Plot")
```

```{r Obs Space 05}
leaf_data %>% 
  select(Type, Length, Width) %>% 
  gather(
    key = Dimension
    ,value = Measurement
    ,-Type
  ) %>% 
  ggplot(aes(x = Measurement, y = ..density.., colour = Type)) +
  geom_histogram(
    alpha = 0.5
    ,binwidth = function(x) 2 * IQR(x) / (length(x)^(1/3))
  ) +
  geom_density() +
  facet_grid(
    Dimension ~ Type
  ) +
  scale_colour_brewer(
    type = "qual"
    ,palette = "Set2"
  ) +
  labs(title = "Figure XX: Density Plot by Type")
```


## Covariance Matrix
```{r Covariance Matrix Combined}
leaf_data %>% 
  select(Length, Width) %>% 
  cov() %>% 
  kable(caption = "Shared Covariance Matrix")
```

```{r Covariance Matrix Seperate}
leaf_data %>% 
  filter(Type == "Cherry") %>% 
  select(Length, Width) %>% 
  cov() %>% 
  kable(caption = "Cherry Covariance Matrix")

leaf_data %>% 
  filter(Type == "Pear") %>% 
  select(Length, Width) %>% 
  cov() %>% 
  kable(caption = "Pear Covariance Matrix")
```

```{r Multinom}
leaf_sample <- 
  100 %>% 
  mvrnorm(
    mu = 
      (leaf_data %>% 
         select(Length, Width) %>% 
         summarize_all(mean) %>% 
         gather(
           key = Variable
           ,value = Value
         ))$Value
    ,Sigma = 
      leaf_data %>% 
      select(Length, Width) %>%  
      cov()
  ) %>% 
  as_tibble() 

leaf_sample %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
    )
  ) +
  geom_density_2d() +
  labs(title = "Simulated Data (All)")

leaf_sample_cherry <- 
  100 %>% 
  mvrnorm(
    mu = 
      (leaf_data %>% 
         filter(Type == "Cherry") %>% 
         select(Length, Width) %>% 
         summarize_all(mean) %>% 
         gather(
           key = Variable
           ,value = Value
         ))$Value
    ,Sigma = 
      leaf_data %>% 
      filter(Type == "Cherry") %>% 
      select(Length, Width) %>%  
      cov()
  ) %>% 
  as_tibble() 

leaf_sample_cherry %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
    )
  ) +
  geom_density_2d() +
  labs(title = "Simulated Data (Cherry)")

leaf_sample_pear <- 
  100 %>% 
  mvrnorm(
    mu = 
      (leaf_data %>% 
         filter(Type == "Pear") %>%
         select(Length, Width) %>% 
         summarize_all(mean) %>% 
         gather(
           key = Variable
           ,value = Value
         ))$Value
    ,Sigma = 
      leaf_data %>% 
      filter(Type == "Pear") %>%
      select(Length, Width) %>%  
      cov()
  ) %>% 
  as_tibble()

leaf_sample_pear %>% 
  ggplot(
    aes(
      x = Width
      ,y = Length
    )
  ) +
  geom_density_2d() +
  labs(title = "Simulated Data (Pear)")
```

```{r Leaf Density}
leaf_test <-
  tibble(
    Number = 1:3
    ,Length = c(8.2, 5.2, 7.6)
    ,Width = c(3.2, 3.8, 4.0)
  )

leaf_test %>% 
  kable()

leaf_data %>% 
  dens_gen(leaf_type = "Cherry", newdata = leaf_test) %>% 
  kable()

leaf_data %>% 
  dens_gen(leaf_type = "Pear", newdata = leaf_test) %>% 
  kable()
```


# Conclusion



